### ISSUE TITLE
Unsafe usage of params.order in HQL query

### ISSUE THREAD

**Issue by xlson** [qbranchcode/Qanban#11]
Commit 4999acb3bf98f6c318da4dd7ea9d4c818c540f3c introduced a HQL query that uses the params object in a unsafe way. This needs to be fixed before the 0.1 release.

Offending code:
eventList = Event.executeQuery("SELECT e FROM Event e, User u WHERE e.userDomainId = u.domainId ORDER BY u.userRealName $params.order OFFSET $params.offset LIMIT $params.max")

**Comment by gardeman** [comment]
Fixed the HQL bug in main view controller. closed by 0b3f1bab59a7c5b51965753642e3f439c367256c
