### ISSUE TITLE
Archive Tab

### ISSUE THREAD

**Issue by gardeman** [qbranchcode/Qanban#15]
If the user changes the title on the archive phase, the title on the tab used to show the archive should have the same title.

Dependent on 'Javascript refactoring'
Seen in v 0.1.0.38 ( standalone mode )

**Comment by xlson** [comment]
Fix in #20

**Comment by gardeman** [comment]
Moved the menu from the inside layout to the main view and added dynamic naiming on the archive tab so that the label shows the title of the archive phase. I also extracted the css from the inside layout to style.css. Closed by 84679db8f53b70a4d8b28c3e6b7038a6103d05c4
