### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by gardeman** [qbranchcode/Qanban#18]
The refresh that's supposed to run every 5 minutes don'twork.

Seen in v 0.1.0.38 ( standalone mode )

**Comment by mirhagen** [comment]
Log and Archive now loads as intended. Board autorefresh is now working. Closed by 1b04d1cc6b04272c97d1276f1a3f546cdd16411c Closed by 1b04d1cc6b04272c97d1276f1a3f546cdd16411c
