### ISSUE TITLE
Find an alternative to MySQL Query Browser for HSQLDB

### ISSUE THREAD

**Issue by xlson** [qbranchcode/Qanban#4]

**Comment by mirhagen** [comment]
DbVisualizer
http://www.dbvis.com/products/dbvis/download/
Available in free edition - Works pretty well.
Seems to "run out of the box"

Usage - Database->Create Database Connection->No Wizard
Database Type: HSQLDB
Driver: HSQLDB embedded
Database URL: jdbc:hsqldb:file:<path to Qanban-dir>/devDB (or prodDB if that's what you use)
Userid: sa

-> Connect
