### ISSUE TITLE
Fix Registration form on the frontpage

### ISSUE THREAD

**Issue by xlson** [qbranchcode/Qanban#7]
Rewrite the form for version 0.1 to create admin users.

Changes:
Add password/password again fields to form
Create all users with the admin role
Remove testadmin/testuser from prod

**Comment by xlson** [comment]
Don't forget to test this with the Qbranch internal AD - creating all users with Admin role might cause problems for us.

**Comment by gardeman** [comment]
closed by 53df6720ddd4041808ea88fd0510d77969c51515
