### ISSUE TITLE
Allow JNDI with HSQLDB in prod

### ISSUE THREAD

**Issue by xlson** [qbranchcode/Qanban#8]
With the current build we have removed JNDI in favor of using HSQLDB as the production database. It's okay for the current release (0.1) but not in the future.

The application should look for a datasource with JNDI but use HSQLDB as a fallback.

**Comment by mirhagen** [comment]
Closes ecaa8a7c5168c3686a8f11e8252979f5b1bee920
Only on master branch, not on RB_0.1
